api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'api'
urlpatterns = [
    # api requests here,
    path('get_products', views.api_get_allproducts, name='api_get_allproducts'),
    path('get_categories', views.api_get_allcategories, name='api_get_allcategories'),
    path('get_stocks', views.get_stocks, name='get_stocks'),
    path('check_account_exist', views.check_account_exist, name='check_account_exist'),
    path('auth_user', views.auth_user, name='auth_user'),
    path('register_user_request', views.register_user_request, name='register_user_request'),
    path('register_user_finish', views.register_user_finish, name='register_user_finish'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_orders', views.get_user_orders, name='get_user_orders'),
    path('get_user_addresses', views.get_user_addresses, name='get_user_addresses'),
    path('delete_user_address', views.delete_user_address, name='delete_user_address'),
    path('create_user_address', views.create_user_address, name='create_user_address'),
    path('change_user_password', views.change_user_password, name='change_user_password'),
    path('create_order_not_auth', csrf_exempt(views.create_order_not_auth), name='create_order_not_auth'),
    path('create_order_auth', csrf_exempt(views.create_order_auth), name='create_order_auth'),
    path('check_promo', views.check_promo, name='check_promo'),
    path('get_critical_info', views.get_critical_info, name='get_critical_info'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('offer/', views.offer, name = 'offer'),
    path('order_created/', views.order_created, name = 'order_created'),
    path('add_item_ajax/', views.add_item_ajax, name = 'add_item_ajax'),
    path('delete_from_cart_ajax/', views.delete_from_cart_ajax, name = 'delete_from_cart_ajax'),
    path('update_cart_info_ajax/', views.update_cart_info_ajax, name = 'update_cart_info_ajax'),
    path('add_quantity_ajax/', views.add_quantity_ajax, name = 'add_quantity_ajax'),
    path('remove_quantity_ajax/', views.remove_quantity_ajax, name = 'remove_quantity_ajax'),
    path('check_in_cart_ajax/', views.check_in_cart_ajax, name = 'check_in_cart_ajax'),
    path('update_cart_total_ajax', views.update_cart_total_ajax, name = 'update_cart_total_ajax'),
    path('create_order_ajax', views.create_order_ajax, name = 'create_order_ajax'),
    path('process_promo_ajax', views.process_promo_ajax, name = 'process_promo_ajax'),
    path('remove_promo_ajax', views.remove_promo_ajax, name = 'remove_promo_ajax'), 
    path('process_bonus_use_ajax', views.process_bonus_use_ajax, name = 'process_bonus_use_ajax'), 
    path('process_bonus_use_cancel_ajax', views.process_bonus_use_cancel_ajax, name = 'process_bonus_use_cancel_ajax'), 
    path('check_set_delivery_discount_ajax', views.check_set_delivery_discount_ajax, name = 'check_set_delivery_discount_ajax'), 
    path('check_set_payment_ajax', views.check_set_payment_ajax, name = 'check_set_payment_ajax'), 
    path('remember_user_info_ajax', views.remember_user_info_ajax, name = 'remember_user_info_ajax'), 
]

food_fabrik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('products.urls')),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('users.urls')),
] 

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:cat_id>', views.category, name = 'category'),
    path('<int:cat_id>/<int:dest_id>', views.destination, name = 'destination'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('stock/', views.stock, name = 'stock'),
    path('stock/<int:stock_id>', views.stock_item, name = 'stock_item'),
    path('callme_mail_ajax/', views.callme_mail_ajax, name = 'callme_mail_ajax'),
]

cart/views.py
from django.shortcuts import render

from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from food_fabrik.settings import * 
from products.models import * 

from django.core.mail import send_mail
from django.conf import settings
from django.core import serializers
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from users.models import is_authorized, get_user, Address



def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key

def get_or_create_cart(request):
    session_key = get_session_key(request)
    current_cart = Cart.objects.get_or_create(
        session_key = session_key,
    )[0],
    return current_cart[0]




def index(request):
    session_key = get_session_key(request)
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    total_discount = cart.get_total_discount()
    categories = Category.objects.all()
    return render(request, 'cart/index.html', {
        'categories': categories,
        'cart': cart,
        'session_key': session_key,
        'total_discount': total_discount, 
    })

def offer(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    user = get_user(request)
    categories = Category.objects.all()
    return render(request, 'cart/offer.html', {
        'categories': categories,
        'cart': cart,
        'user': user,
    })

def order_created(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)

    categories = Category.objects.all()
    return render(request, 'cart/order_created.html', {
        'categories': categories,
        'cart': cart,
    })


def add_item_ajax(request):
    cart = get_or_create_cart(request)
    is_new = 'yes'
    pr_id = request.GET['product_id']
    pr = Product.objects.get(
        id = pr_id,
    )
    if (Item.objects.filter(
        product = pr,
        cart = cart,
    ).exists()):
        item = Item.objects.get(
           product = pr,
           cart = cart,
        )
        item.delete()
        in_cart = 'no'
        # item = Item.objects.get(
        #    cart = cart,
        #     pr_id = pr.id, 
        # )
        # item.quantity += 1
        # item.save()
    else:
        item = Item(
            product = pr,
            cart = cart,
        )
        item.save()
        in_cart = 'yes'
    
    return JsonResponse({
        'is_new': is_new,
        'in_cart': in_cart,
        'product_name': pr.name,
    }, status = 200 )

def delete_from_cart_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['item_id']
    item = Item.objects.get(
        cart = cart,
        id = item_id
    )
    item.delete()
    # cart.item_set.remove(item)
    return JsonResponse({
        'deleted': 'yes'
    }, status = 200)

def update_cart_info_ajax(request):
    cart = get_or_create_cart(request)
    cart_total = cart.get_total()
    cart_quantity = cart.item_set.count()
    total_discount = cart.get_total_discount()
    return JsonResponse({
        'cart_total': cart_total,
        'cart_quantity': cart_quantity,
        # 'deleted': 'yes',
        'total_discount': total_discount,
    }, status = 200)

def remove_quantity_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['item_id']
    item = Item.objects.get(
        cart = cart,
        id = item_id,
    )
    if item.quantity == 1:
        item.delete()
        is_removed = 'yes'
        return JsonResponse({
        'is_removed': is_removed,
    }, status = 200)
    else:
        item.quantity -= 1
        item.save()
        is_removed = 'no'
        if (item.has_sale()):
            has_sale = 'yes'
            pr_price = item.product_price()
            pr_sale = item.product_sale_price()
            discount_val = item.discount_val()
            return JsonResponse({
            'has_sale': has_sale,
            'is_removed': is_removed,
            'item_price': pr_price,
            'item_sale': pr_sale,
            'item_discount_val': discount_val,
            'item_quantity': item.quantity,
        }, status = 200)
        else:
            has_sale = 'no'
            pr_price = item.product_price()
            return JsonResponse({
            'has_sale': has_sale,
            'is_removed': is_removed,
            'item_price': pr_price,
            'item_quantity': item.quantity,
        }, status = 200)

        
    

def add_quantity_ajax(request):
    print('request is here')
    cart = get_or_create_cart(request)
    try:
        request.GET['from_prpage']
        item_id = request.GET['item_id']
        item = Item.objects.get(
            cart = cart,
            product__id = item_id,
        )
    except:
        item_id = request.GET['item_id']
        item = Item.objects.get(
        cart = cart,
        id = item_id,
        )

    item.quantity += 1
    item.save()

    if item.has_sale():
        has_sale = 'yes'
        pr_price = item.product_price()
        pr_sale = item.product_sale_price()
        discount_val = item.discount_val()
        return JsonResponse({
            'has_sale': has_sale,
            'item_price': pr_price,
            'item_sale': pr_sale,
            'item_discount_val': discount_val,
            'item_quantity': item.quantity,
        }, status = 200)
    else:
        has_sale = 'no'
        pr_price = item.product_price()
        return JsonResponse({
        'has_sale': has_sale,
        'item_price': pr_price,
        'item_quantity': item.quantity,
    }, status = 200)

def check_in_cart_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['product_id']
    in_cart = ''
    if (Item.objects.filter(
        cart = cart,
        product__id = item_id).exists()):
        in_cart = 'yes'
        current_item = Item.objects.get(
            cart = cart,
            product__id = item_id
        )
        return JsonResponse({
            'in_cart': in_cart,
            'quantity': current_item.quantity,
        }, status = 200)
    else:
        in_cart = 'no'
        return JsonResponse({
            'in_cart': in_cart,
        }, status = 200)


def update_cart_total_ajax(request):
    cart = get_or_create_cart(request)
    cart_total = cart.items_in_cart()
    return JsonResponse({
        'cart_total': cart_total,
    }, status = 200)


def create_order_ajax(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    cart_total = cart.items_in_cart()
    purchase_amount = cart.get_total()
    coupon = cart.coupon
    bonus_used = cart.bonus_used
    delivery_discount_use = cart.delivery_discount_use
    # name = urllib.parse.unquote(request.GET['name'])
    # phone = urllib.parse.unquote(request.GET['phone'])
    # delivery = urllib.parse.unquote(request.GET['delivery'])
    # address = urllib.parse.unquote(request.GET['address'])
    # payment = urllib.parse.unquote(request.GET['payment'])

    name = request.GET['name']
    phone = request.GET['phone']
    delivery = request.GET['delivery']
    address = request.GET['address']
    payment = request.GET['payment']

    is_auth = is_authorized(request)
    if (is_auth):
        user = get_user(request)
        if bonus_used:
            user.bonus -= bonus_used
            user.save()
        if coupon:
            coupon.users.add(user)
        if delivery == 'Самовывоз':
            address =  'Самовывоз'
            pass
        else:
            address = Address.objects.get(
                id = delivery
            ).get_full()
            delivery = 'Курьер'
        bonus_gained = calc_bonus_gained(user, purchase_amount)
    else:
        user = None
        bonus_gained = 0
    

    new_order = Order(
        user = user,
        name = name,
        phone = phone,
        delivery = delivery,
        address = address,
        payment = payment,
        bonus_gained = bonus_gained,
        bonus_used = bonus_used,
        amount = purchase_amount,
        coupon = coupon,
        delivery_discount_use = delivery_discount_use,
    )
    new_order.save()
    cart.coupon = None
    cart.bonus_used = None

    # add bonus gained to user and save the user
    # if (is_auth):
    #     user.bonus += bonus_gained
    #     user.save()


    cart_items_mail = []
    order_price_mail = 0
    cart.save()
    for item in cart.item_set.all():
        new_order.item_set.add(item)
        cart.item_set.remove(item)
        if item.has_sale():
            price = item.product.sale_price
        else:
            price = item.product.price
        order_price_mail += price
        cart_items_mail.append([item.product.name, item.quantity, price])
    all_items = new_order.item_set.all()
    new_order.save()
    # try:
    #     email_context = {
    #         'name': name,
    #         'phone': phone,
    #         'order_price': order_price_mail,
    #         'order_items': all_items,
    #         'address': address,
    #         'delivery': delivery,
    #         'payment': payment,
    #     }
    #     admin_html_message = render_to_string('cart/blocks/mail_template.html', email_context)
    #     admin_html_message_plain = strip_tags(admin_html_message)
    #     send_mail(
    #         'Новый заказ на сайте!',
    #         admin_html_message_plain,
    #         settings.EMAIL_HOST_USER,
    #         [
    #         # 'worlddelete0@mail.ru', 
    #         # 'fudfabrik@gmail.com',
    #         # '161085ap@mail.ru',
    #         # 'worlddelete0@yandex.ru',
    #         ],
    #         html_message= admin_html_message,
    #         # 'fudfabrik@gmail.com'
    #         )
    # except:
    #     pass

    return JsonResponse({
        'order_created': 'yes',

templates/cart/offer.html
{% extends '../products/base.html' %}
{% load products_extras %}

{% block content %}

<div class="cart__main__title">

    {% include './blocks/space20.html' %}
    <div class="nice__title2__left">
        Оформление заказа
    </div>

</div>

<div class="offer__page__container">
    <div class="offer__page__block1">
        <div class="offer__page__block1__sub">
            <div class="offer__page__block1__sub__title">
                <span>
                    Контактные данные
                </span>
            </div>
            <div class="offer__page__block1__sub__content">
                <div class="error__message"
                id="error_name_phone">
                    <span>
                    Введите ваше имя и телефон
                    </span>
                </div>
                <div class="offer__page__block1__sub__content__form">
                <input type="text"
                placeholder="Имя"
                value="{{ user.name }}"
                autocomplete="off"
                class="cart__input"
                name="person_name">
                <input type="text"
                value="{{ user.phone }}"
                placeholder="Телефон"
                autocomplete="off"
                class="cart__input"
                name="person_phone">
                </div>

            </div>


            <div class="offer__page__block1__sub__title">
                <span>
                    Способ доставки
                </span>
            </div>
            <div class="error__message"
                id="error_delivery">
                    <span>
                    Выберите способ доставки
                    </span>
                </div>
            <div class="delivery__block__main">
                <div class="delivery__block__main__card
                delivery__method delivery__method__cura"
                value="курьер"
                data-toogle="#cart_input_cura">
                    <span>
                        Курьером 
                    </span>
                </div>
                <div class="delivery__block__main__card
                delivery__method delivery__method__byclient"
                value="самовывоз"
                data-toogle="#cart_input_own">
                    <span>
                        Самовывоз 
                    </span>
                </div>
            </div>


            <div class="delivery__subinfo__container">

            {% if user %}
                <div id="cart_input_cura">
                        <div class="nice_title medium center bold pd15">
                            <span>
                                Выберите адрес доставки
                            </span>
                        </div>
                        <div class="cart_delivery_authorized">
                            {% include './blocks/offer_address_block.html' %}      
                        </div>
                        <div class="nice_button pointer noselect center">
                            <span class="add_address_form_button need_render">
                                Добавить адрес
                            </span>
                        </div>
                </div>
                {% else %}
                    <input type="text"
                    placeholder="Адрес доставки (улица, дом, квартира)"
                    autocomplete="off"
                    class="cart__input"
                    id="cart_input_cura"
                    name="delivery_address">
            {% endif %}
            <span
            id="cart_input_own">
                <div class="nice_title medium center bold pd15">
                    <span>
                        Адрес самовывоза:
                    </span>
                </div>
                г. Краснодар, ул. Монтажников, 12.
            </span>
            </div>


            <div class="offer__page__block1__sub__title">
                <span>
                    Способ оплаты
                </span>
            </div>
            <div class="error__message"
                id="error_payment">
                    <span>
                    Выберите способ оплаты
                    </span>
                </div>

            <div class="delivery__block__main">
                <div class="delivery__block__main__card
                payment__method payment__method_cash"
                value="наличные">
                    <span>
                        Наличными 
                    </span>
                </div>
                <div class="delivery__block__main__card
                payment__method payment__method_beznal"
                value="безнал">
                    <span>
                        Безналичный расчет
                    </span>
                </div>
            </div>


        </div>
    </div>
    <div class="offer__page__block2">
        <div class="offer__page__block2__content">
            <div class="offer__page__block2__content__item">
                <div class="offer__page__block2__content__item__first">
                    <span class="your__cart__block__title">
                        Ваш заказ
                    </span>
                </div>
                <div class="offer__page__block2__content__item__second">
                    <a class="offer__cart__back"
                    href="{% url 'cart:index' %}">
                        Редактировать
                    </a>
                </div>
            </div>

            {% for item in cart.item_set.all  %}

            <div class="offer__page__block2__content__item">

                <div class="offer__page__block2__content__item__first">
                
                    <div class="offer__page__block2__content__item__prinfo">
                        {% modify_imgsrc item.product.imgsrc as imgsrc %}
                        <img src="{{ imgsrc }}" alt="">
                        <div class="offer__page__block2__content__item__prinfo__second">
                            <a class="offer__page__block2__content__item__prinfo__second__name"
                            href="{% url 'products:product' item.product.id %}">
                                {{ item.product.name }}
                            </a>
                            <span class="offer__page__block2__content__item__prinfo__second__name">
                                {{ item.quantity }} шт.
                            </span>
                        </div>
                    </div>
                </div>
                <div class="offer__page__block2__content__item__second">
                    {% if item.has_sale %}
                        <span>
                            {{ item.product.sale_price }}
                        </span>
                        {% else %}
                            <span>
                                {{ item.product.price }}
                            </span>
                    {% endif %}
                </div>

            </div>

            {% endfor %}
            {% if user %}
            {% include './blocks/bonus_use_block.html' %}
            {% endif %}
        <div class="offer__page__block2__content__item">
            <div class="offer__page__block2__content__item__first">
                <span class="your__cart__block__title3">
                    Итого
                </span>
            </div>
            <div class="offer__page__block2__content__item__second">
                <span class="your__cart__block__value4">
                    {{ cart.get_total }} Р
                </span>
            </div>
        </div>

        <div class="">
            <a class="cart__checkout__button">
                <span>
                    Разместить заказ
                </span>
            </a>
        </div>


        </div>
    </div>
</div>


<script>
    $(".main__site__wrapper__main").addClass("bg1")
    check_set_delivery_payment()
    check_set_user_info()

    function check_set_user_info() {
        var user_name = "{{ cart.current_name }}"
        var user_phone = "{{ cart.current_phone }}"
        $("input[name='person_name']").attr('value', user_name)
        $("input[name='person_phone']").attr('value', user_phone)
    }
    function cart_remember_user_info() {
        var user_name = $("input[name='person_name']").val()
        var user_phone = $("input[name='person_phone']").val()
        console.log(user_name, user_phone);
        $.ajax({
            url: "{% url 'cart:remember_user_info_ajax' %}",
            data: {
                'user_name': user_name,
                'user_phone': user_phone,
            }, success: function() {
            }
        })
    }
    function check_set_delivery_payment() {
        var delivery_method = "{{ cart.delivery_method }}"
        var payment_method = "{{ cart.payment_method }}"
        console.log('delivery method is');
        console.log(delivery_method);
        if (delivery_method == 1) {
            $(".delivery__method__cura").addClass('active')
            setDeliveryActive($('.delivery__method__cura'))
        }
        if (delivery_method == 2) {
            $(".delivery__method__byclient").addClass('active')
            setDeliveryActive($('.delivery__method__byclient'))
        }
        if (payment_method == 1) {
            $(".payment__method_cash").addClass("active")
            setPaymentActive($(".payment__method_cash"))
        }
        if (payment_method == 2) {
            $(".payment__method_beznal").addClass("active")
            setPaymentActive($(".payment__method_beznal"))
        }
    }

    $('.delivery__method').click(function() {
        delivery_method = $(this).attr("value")
        console.log('start count if need to apply delivery discount')
        console.log('delivery method is', delivery_method)
        $.ajax({
            url: "{% url 'cart:check_set_delivery_discount_ajax' %}",
            data: {
                'delivery_method': delivery_method,
            }, success: function(data) {
                console.log('response data is', data)
                cart_remember_user_info()
                window.location.reload()
            }
        })
        setDeliveryActive(this)
    })

    $(".payment__method").click(function() {
        payment_method = $(this).attr("value")
        $.ajax({
            url: "{% url 'cart:check_set_payment_ajax' %}",
            data: {
                'payment_method': payment_method,
            }, success: function(data) {
                console.log('response data is', data)
                cart_remember_user_info()
                window.location.reload()
            }
        })
        setPaymentActive(this)
    })

    $(".cart__checkout__button").click(function() {
        $('#error_name_phone').removeClass("show")
        $('#error_delivery').removeClass("show")
        $('#error_payment').removeClass("show")

        var error_id
        var can_make_order = 'yes'


        var name = $("input[name='person_name']").val()
        var phone = $("input[name='person_phone']").val()
        var payment = $(".payment__method.active").attr("value")

        var user = "{{ user.id }}"
        if (user == false) {
            var delivery = $(".delivery__method.active").attr("value")
            if (delivery == 'курьер') {
            var address = $("input[name='delivery_address']").val()
            } else {
                var address = 'Самовывоз'
            }
            if (delivery === undefined) {
            $('#error_delivery').addClass("show")
            error_id = '#error_delivery'
            can_make_order = 'no'
            }
            if (address.length == 0) {
            $('#error_delivery').addClass("show")
            error_id = '#error_delivery'
            can_make_order = 'no'
            }
        } else {
            var delivery_method = $(".delivery__method.active").attr("value")
            if (delivery_method == 'курьер') {
                var delivery = $("input[name='delivery_address_auth']:checked").val()
                if (delivery === undefined) {
                $('#error_delivery').addClass("show")
                error_id = '#error_delivery'
                can_make_order = 'no'
                }
                address = 'need_specify'
            } else {
                var delivery = 'Самовывоз'
                address = ''
            }
        }
        

        
        if (name.length == 0) {
            $('#error_name_phone').addClass("show")
            error_id = '#error_name_phone'
            can_make_order = 'no'
        }
        if (phone.length == 0) {
            $('#error_name_phone').addClass("show")
            error_id = '#error_name_phone'
            can_make_order = 'no'
        }
        if (payment === undefined) {
            $('#error_payment').addClass("show")
            error_id = '#error_payment'
            can_make_order = 'no'
        }
        if (error_id != undefined) {
        $([document.documentElement, document.body]).animate({
        scrollTop: $(error_id).offset().top - 100
    }, 1000);
        }


        if (can_make_order == 'yes') {
            console.log('can make an order')
        $.ajax({
            url: "{% url 'cart:create_order_ajax' %}",
            data: {
                'name': name,
                'phone': phone,
                'delivery': delivery,
                'address': address,
                'payment': payment,
            },
            success: function(data) {
                created = data['order_created']
                if (created == 'yes') {
                    console.log('order is created')
                    document.location.href = "{% url 'cart:order_created' %}"
                }
            }
        });

        }
        
    })

</script>

{% endblock content %}

templates/cart/order_created.html
{% extends '../products/base.html' %}

{% block content %}
    <div class="order__created__container">
        <i class="gg-check created__check">
        </i>
        <div class="order__created__container__title">
            Ваш заказ размещен!
        </div>
        <div class="order__created__container__subtitle">
            В ближайшее время с вами свяжется менеджер.
        </div>
        <div class="order__created__container__link">
            <a href="{% url 'products:index' %}">
                <span class="order__created__container__button">
                    Продолжить покупки
                </span>
            </a>
            <!-- <a href="#">
                <span class="order__created__container__button">
                    Личный кабинет
                </span>
            </a> -->
        </div>
    </div>
{% endblock content %}