api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'api'
urlpatterns = [
    # api requests here,
    path('get_products', views.api_get_allproducts, name='api_get_allproducts'),
    path('get_categories', views.api_get_allcategories, name='api_get_allcategories'),
    path('get_stocks', views.get_stocks, name='get_stocks'),
    path('check_account_exist', views.check_account_exist, name='check_account_exist'),
    path('auth_user', views.auth_user, name='auth_user'),
    path('register_user_request', views.register_user_request, name='register_user_request'),
    path('register_user_finish', views.register_user_finish, name='register_user_finish'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_orders', views.get_user_orders, name='get_user_orders'),
    path('get_user_addresses', views.get_user_addresses, name='get_user_addresses'),
    path('delete_user_address', views.delete_user_address, name='delete_user_address'),
    path('create_user_address', views.create_user_address, name='create_user_address'),
    path('change_user_password', views.change_user_password, name='change_user_password'),
    path('create_order_not_auth', csrf_exempt(views.create_order_not_auth), name='create_order_not_auth'),
    path('create_order_auth', csrf_exempt(views.create_order_auth), name='create_order_auth'),
    path('check_promo', views.check_promo, name='check_promo'),
    path('get_critical_info', views.get_critical_info, name='get_critical_info'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('offer/', views.offer, name = 'offer'),
    path('order_created/', views.order_created, name = 'order_created'),
    path('add_item_ajax/', views.add_item_ajax, name = 'add_item_ajax'),
    path('delete_from_cart_ajax/', views.delete_from_cart_ajax, name = 'delete_from_cart_ajax'),
    path('update_cart_info_ajax/', views.update_cart_info_ajax, name = 'update_cart_info_ajax'),
    path('add_quantity_ajax/', views.add_quantity_ajax, name = 'add_quantity_ajax'),
    path('remove_quantity_ajax/', views.remove_quantity_ajax, name = 'remove_quantity_ajax'),
    path('check_in_cart_ajax/', views.check_in_cart_ajax, name = 'check_in_cart_ajax'),
    path('update_cart_total_ajax', views.update_cart_total_ajax, name = 'update_cart_total_ajax'),
    path('create_order_ajax', views.create_order_ajax, name = 'create_order_ajax'),
    path('process_promo_ajax', views.process_promo_ajax, name = 'process_promo_ajax'),
    path('remove_promo_ajax', views.remove_promo_ajax, name = 'remove_promo_ajax'), 
    path('process_bonus_use_ajax', views.process_bonus_use_ajax, name = 'process_bonus_use_ajax'), 
    path('process_bonus_use_cancel_ajax', views.process_bonus_use_cancel_ajax, name = 'process_bonus_use_cancel_ajax'), 
    path('check_set_delivery_discount_ajax', views.check_set_delivery_discount_ajax, name = 'check_set_delivery_discount_ajax'), 
    path('check_set_payment_ajax', views.check_set_payment_ajax, name = 'check_set_payment_ajax'), 
    path('remember_user_info_ajax', views.remember_user_info_ajax, name = 'remember_user_info_ajax'), 
]

food_fabrik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('products.urls')),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('users.urls')),
] 

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:cat_id>', views.category, name = 'category'),
    path('<int:cat_id>/<int:dest_id>', views.destination, name = 'destination'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('stock/', views.stock, name = 'stock'),
    path('stock/<int:stock_id>', views.stock_item, name = 'stock_item'),
    path('callme_mail_ajax/', views.callme_mail_ajax, name = 'callme_mail_ajax'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('orders/', views.orders, name = 'orders'),
    path('orders/<int:order_id>', views.order_item, name = 'order_item'),
    path('login_ajax', views.login_ajax, name = 'login_ajax'),
    path('login_out_ajax', views.login_out_ajax, name = 'login_out_ajax'),
    path('login', views.login, name = 'login'),
    path('register', views.register, name = 'register'),
    path('settings', views.settings, name = 'settings'),
    path('address', views.address, name = 'address'),
    path('address_action_ajax', views.address_action_ajax, name = 'address_action_ajax'),
    path('promo', views.promo, name = 'promo'),
    path('restore', views.restore, name = 'restore'),
    path('register_ajax', views.register_ajax, name = 'register_ajax'),
    path('restore_ajax', views.restore_ajax, name = 'restore_ajax'),
    path('change_password_ajax', views.change_password_ajax, name = 'change_password_ajax'),
]

products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    slug = models.CharField(default = '', max_length = 300)
    name = models.CharField(default = '', max_length = 300)
    imgsrc = models.ImageField(upload_to="static/images/products", default = '')
    display_priority = models.IntegerField(default = 0,)
    def __str__(self):
        return self.name 

# class Destination(models.Model):
#     name = models.CharField(default = '', max_length = 300)
#     category = models.ForeignKey(Category,
#     on_delete=models.CASCADE)
#     def __str__(self):
#         return self.name

        
class Product(models.Model):
    # attributes = models.ManyToManyField(Attributeitem)
    # attributes = models.ManyToManyField(Attribute)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, default = None,
    null = True, blank = True)

    name = models.CharField(default = '', max_length = 300)
    price = models.IntegerField(default = 0)
    sale_price = models.IntegerField(default = 0,)
    ves = models.CharField(default = '', max_length = 300)
    description = models.CharField(default = '', max_length = 2000)
    # imgsrc = models.ImageField(upload_to='static/images', blank = True, null = True)
    imgsrc = models.ImageField(upload_to="static/images/products", default = '')
    display_priority = models.IntegerField(default = 0)
    def __str__(self):
        return self.name + ' ' + str(self.get_price()) + ' ₽'


    def get_price(self):
        if self.sale_price > 0:
            return self.sale_price
        else:
            return self.price
    def discount_perc(self):
        return int(((self.price - self.sale_price) / self.price) * 100)
    def discount_val(self):
        return int(self.price - self.sale_price)
    def has_sale(self):
        if self.sale_price > 0:
            return True
        else:
            return False


# class Attribute(models.Model):
#     name = models.CharField(default = '', max_length = 300) 
#     category = models.ForeignKey(Category,
#     on_delete=models.CASCADE, default = None,)
#     product = models.ForeignKey(Product,
#         on_delete=models.CASCADE, default = None,
#     )
    # def __str__(self):
    #     return self.name 

# class Attributeitem(models.Model):
#     name = models.CharField(default = '', max_length = 300)
#     attr = models.ForeignKey(
#         Attribute, on_delete=models.CASCADE,
#     )
#     def __str__(self):
#         return self.name 

class Stock(models.Model):
    name = models.CharField(default = '', max_length = 300)
    description = models.CharField(default = '', max_length = 2000)
    imgsrc = models.ImageField(upload_to="static/images/products")
    display_priority = models.IntegerField(default = 0,)

    def __str__(self):
        return self.name

def deleteall():
    pr = Product.objects.all()
    # dest = Destination.objects.all()
    ct = Category.objects.all()
    # st = Stock.objects.all()
    # st.delete()
    ct.delete()
    # dest.delete()
    pr.delete()

    print('all is deleted')

products/views.py
from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from food_fabrik.settings import * 
from cart.models import * 

from django.core.mail import send_mail
from django.conf import settings


# Create your views here.

def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key  

def get_or_create_cart(request):
    session_key = get_session_key(request)
    current_cart = Cart.objects.get_or_create(
        session_key = session_key,
    )[0],
    return current_cart[0]



def index(request):
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    categories = Category.objects.all().order_by('display_priority')
    # destinations = Destination.objects.all()
    products = Product.objects.all()
    sale_products = Product.objects.filter(
        sale_price__gte = 1
    )
    # return HttpResponse('Наша доставка еды скоро откроется!')
    return render(request, 'products/index.html', {
        'categories': categories,
        'products': products,
        'session_key': session_key,
        'cart': cart,
        'sale_products': sale_products,
        # 'destinations': destinations,
    })
def product(request, product_id):
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    current_product = Product.objects.get(id = product_id)
    return render(request, 'products/product.html', {
        'product': current_product,
        'cart': cart,
        'session_key': session_key,
    })



def destination(request, cat_id, dest_id):
    session_key = get_session_key(request)
    current_cat = Category.objects.get(
        id = cat_id,
    )
    current_dest = Destination.objects.get(
        category = current_cat,
        id = dest_id,
    )
    products = current_dest.product_set.all()
    return render(request, 'products/dest.html', {
        'current_cat': current_cat,
        # 'current_dest': current_dest,
        'products': products,
    })

def category(request, cat_id):
    session_key = get_session_key(request)
    
    current_cat = Category.objects.get(
        id = cat_id,
    )
    
    products = Product.objects.filter(
        category = current_cat,
    )
    return render(request, 'products/category.html', {
        'current_cat': current_cat,
        # 'current_dest': current_dest,
        'products': products,
    })

def stock(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    stocks = Stock.objects.all().order_by('-display_priority')
    return render(request, 'products/stock.html', {
        'cart': cart,
        'stocks': stocks,
    })
def stock_item(request, stock_id):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    current_stock = Stock.objects.get(
        id = stock_id
    )
    print('stock id is :', current_stock.id)
    return render(request, 'products/stock_item.html', {
        'cart': cart,
        'stock': current_stock,
    })

def callme_mail_ajax(request):
    user_phone = request.GET['phone']
    print('user phone is: ', user_phone)

    try:
        send_mail(
            'Заявка на обратный звонок!',
            'Номер телефона: {} '.format(user_phone),
            settings.EMAIL_HOST_USER,
            [
            # 'worlddelete0@mail.ru', 
            # 'fudfabrik@gmail.com',
            'fabrika-edi@yandex.ru',
            # '161085ap@mail.ru',
            # 'worlddelete0@yandex.ru',
            ],
            # 'fudfabrik@gmail.com'
            )
        print('email is sent')
    except:
        pass
    
    return JsonResponse({
        'complete': True,
    }, status = 200)

templates/products/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вкусная кухня</title>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/jquery_mask_input.js' %}"></script>

    <script src="{% static 'js/wayp/noframework.waypoints.min.js' %}"></script>
    <script src="{% static 'js/wayp/sticky.min.js' %}"></script>

    <script src="{% static 'plugins/jquery.magnific-popup.js' %}"></script>



    <link rel="stylesheet" href="{% static 'plugins/magnific-popup.css' %}">

    <script async src="https://kit.fontawesome.com/bca16a3855.js" crossorigin="anonymous"></script>
    <link href='https://css.gg/css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'slick/slick.css'%}">
    <link rel="stylesheet" href="{% static 'slick/slick-theme.css'%}">

    <link rel="stylesheet" href="{% static 'js/owlcarousel/owl.carousel.css'%}">
    <link rel="stylesheet" href="{% static 'js/owlcarousel/owl.theme.default.css'%}">


    

</head>
<body>

    {% block main_header %}
    <div class="main__header__block__wrapper">

    <div class="main__header__block">
        {% include './header.html' %}
    </div>
    {% endblock main_header %}

    </div>

    <div class="main__site__wrapper__main">


        <div class="main__site__wrapper">
            {% block content %}

            {% endblock content %}
             
        </div>

       

    </div>

    {% include './footer.html' %}

    {% include './blocks/popup_form.html' %}


    {% include '../users/change_password_form.html' %}

    {% include '../users/add_address_form.html' %}

    {% include '../users/delete_address_form.html' %}




    <script src="{% static 'js/owlcarousel/owl.carousel.js' %}"></script>

    <script>

var sticky = new Waypoint.Sticky({
    element: $('.main__header__block'), // Add in your CSS selector sticky target
    // direction: 'down right',
  })

$(".add_address_form_button").click(function() {
        if ($(this).hasClass('need_render')) {
            $(".add_address_button").addClass('need_render')
        }
        openAddAddressForm()
    })

$(".logout_button_submit").click(function() {
    $.ajax({
        url: "{% url 'users:login_out_ajax' %}",
        data: {
        }, success: function(data) {
            window.location.href = '/'
        }
    })
})
function openChangePasswordForm() {
            $('#change_password_form').addClass('show')
            $('.pform__wrap__wrapper').addClass('show')
        }
function closeChangePasswordForm() {
    $('#change_password_form').removeClass('show')
    $('.pform__wrap__wrapper').removeClass('show')
}
function openAddAddressForm() { 
            $('#add_address_form').addClass('show')
            $('.pform__wrap__wrapper').addClass('show')
        }
function closeAddAddressForm() {
    $('#add_address_form').removeClass('show')
    $('.pform__wrap__wrapper').removeClass('show')
}
function openChangeAddressForm() {
            $('#change_address_form').addClass('show')
            $('.pform__wrap__wrapper').addClass('show')
        }
function closeChangeAddressForm() {
    $('#change_address_form').removeClass('show')
    $('.pform__wrap__wrapper').removeClass('show')
}
function openDeleteAddressForm() {
        $('#delete_address_form').addClass('show')
        $('.pform__wrap__wrapper').addClass('show')
    }
function closeDeleteAddressForm() {
    $('#delete_address_form').removeClass('show')
    $('.pform__wrap__wrapper').removeClass('show')
}


$(".main__header__phone__callme").click(function() {
        current_form = $("#main__popup")
        showModal(current_form)
    })

$(".pform__wrap__close").click(function() {
    closeModal()
})
$(".pform__wrap__wrapper").click(function() {
    closeModal()
})


function updateCartTotal() {
  $.ajax({
    url: "{% url 'cart:update_cart_total_ajax' %}",
    data: {
      'someinfo': 'someinfo',
    },
    success: function(data) {
      var total = data['cart_total']
        $(".count__label").html(total)
    }
  })
}

        $(".product__addtocart__global").click(function() {
            showLoader1(this)
            var this_main = this
            setTimeout(
                function() {
                    addProductToCart(this_main)
                },
                500
            )
            // ajax ends here
        });
        
        function changeButtonCart(in_cart, item) {
            if (in_cart == 'yes') {
                console.log(item.children())
                item.html("<span class='in__cart__buttonstyle'> Удалить с корзины</span>")
            } else {
                item.html("<span class='not__incart__buttonstyle'>В корзину</span>")
            }
        }

        function addProductToCart(product_block) {
            current_item = $(product_block)
            var current_pr_id = $(product_block).attr("value")
            // ajax start here
            $.ajax({
                url: "{% url 'cart:add_item_ajax' %}",
                data: {
                    'product_id': current_pr_id,
                },
                success: function(data) {
                    var in_cart = data['in_cart']
                    var product_name = data['product_name']
                    changeButtonCart(in_cart, current_item)
                    updateCartTotal()
                    showAddedDialog(in_cart, product_name)
                }
            });
        }
        function addProductToCart2(product_block) {
            current_item = $(product_block)
            var current_pr_id = $(product_block).attr("value")
            // ajax start here
            $.ajax({
                url: "{% url 'cart:add_item_ajax' %}",
                data: {
                    'product_id': current_pr_id,
                },
                success: function(data) {
                    var in_cart = data['in_cart']
                    var quantity = data['quantity']
                    updateCartTotal()
                }
            });
        }
        
        function openMobileMenu() {
            $(".header__popup__mobile").addClass("show")
            $(".header__popub__mobile__close").addClass("show")
            $("body").addClass("hidden")
        }
        function closeMobileMenu() {
            $(".header__popup__mobile").removeClass("show")
            $(".header__popub__mobile__close").removeClass("show")
            $("body").removeClass("hidden")
        }
        
        $(".check__block").click(function() {
            $("#map_loc_block").removeClass("show")
            $("#map_delivery_block").removeClass("show")
            $(".check__block").removeClass("active")
            $(this).addClass('active')
            map = $(this).attr("value")
            $(map).addClass("show")
        })

        function showLoader1(item) {
            $.get("{% static 'svg/loader_1.html' %}", function(response) {
                var loader = response
                console.log(loader)
                child = $(item).children('span')
                if ($(child).hasClass('in__cart__buttonstyle')) {
                    $(item).children('span').html(loader)
                    $(".loader").addClass("show")
                    console.log('it is in cart')
                } else {
                    $(item).children('span').html(loader)
                    $(".loader").addClass("show")
                    $(".loader").addClass("white")
                }
            })
        }
        function showAddedDialog(in_cart, product_name) {
            if (in_cart == 'yes') {
                $(".added__dialog").addClass("show")
                $(".added__dialog").children('div').children('span').html(
                    product_name + ' теперь в корзине'
                )
                setTimeout(function() {
                 $(".added__dialog").removeClass("show")   
                }, 1500)
                
            } else {
                $(".added__dialog").addClass("show red")
                $(".added__dialog").children('div').children('span').html(
                    product_name + ' удален с корзины'
                )
                setTimeout(function() {
                 $(".added__dialog").removeClass("show")   
                 $(".added__dialog").removeClass("red")   
                }, 1200)
            }
        }

$("#pform_button").click(function() {
  $(".input__empty__error").removeClass("show")
  var phone = $("#input_phone").val() 
  console.log(phone.length)
  if (phone.length == 0) {
      console.log('вы ничего не ввели')
      $(".input__empty__error").addClass("show")
  } else {

    $.ajax({
        url: "{% url 'products:callme_mail_ajax' %}",
        data: {
            'phone': phone
        },
        success: function(response) {
            $(".pform__container").addClass('hide')
            $(".pp__container").addClass('show')
            setTimeout(function() {
                closeModal()
            }, 4000)
        }
    })

    
    
}

})

    </script>


</body>
</html>

templates/products/category.html
<div>
    {{ current_cat.slug }} <br>
    {{ current_cat.name }} <br
</div>

<div>
    {% for product in products  %}
        <div>
        ------------------- <br>
            {{ product.name }} {{ product.price }} 
            <br>
            {% for attr in product.attribute_set.all  %}
                {{ attr.name }}
                {% for attritem in attr.attributeitem_set.all  %}
                   | {{ attritem.name }} | 
                {% endfor %} <br>
            {% endfor %}
            {% comment %} {% for attr in product.attributes.all %}
                {{ attr.attr.name }}  {{ attr.name }} 
            {% endfor %} {% endcomment %}
            {% comment %} {% for attr in product.attributes.all  %}
                {{ attr.name }} 
                {% for attr_item in attr.attributeitem_set.all  %}
                    {{ attr_item.name }} 
                {% endfor %}  <br>
            {% endfor %} {% endcomment %}
        ------------------- <br>
        </div>
    {% endfor %}
</div>

templates/products/dest.html
<div>
    {{ current_cat.slug }} <br>
    {{ current_cat.name }} <br>
    {{ current_dest }}
</div>

<div>
    {% for product in products  %}
        <div>
        ------------------- <br>
            {{ product.name }} {{ product.price }} <br>
            {% for dest in product.destination.all  %}
                <span style="color: green;">
                    {{ dest.name }}
                </span>
            {% endfor %}
        ------------------- <br>
        </div>
    {% endfor %}
</div>

templates/products/footer.html
{% load static %}
<div class="main__footer">
    <div class="footer__container">
        <div class="footer__container__block">
            <div class="footer__container__block__title">
                меню
            </div>
            <div class="footer__container__block__menu">
                <a
            href="{% url 'products:index' %}#delivery__menu__title"
            class="">
                Меню доставки
            </a>
            <a href="{% url 'products:stock' %}">
                Акции
            </a>
            <a
            href="{% url 'products:index' %}#contact_info_main">
                Контакты
            </a>
            </div>
        </div>
        <!-- contact block -->
        <div class="footer__container__block">
            <div class="footer__container__block__title">
                сделать заказ
            </div>
            <div class="footer__container__block__info">
                <i class="fa fa-phone-alt"></i>
                <a href="tel:78611511254"
                class="footer__container__block__info__tel">
                    +7 (861)-151-12-54
                </a>
            </div>
            <div class="footer__container__block__info">
                <i class="fa fa-clock"></i>
                <span>
                    пн-пт: 12:00 - 00:00
                </span>
            </div>
            <div class="footer__container__block__info">
                <i class="fa fa-clock"></i>
                <span>
                    сб-вс: 11:00 – 00:00
                </span>
            </div>
        </div>
    </div>
</div>

templates/products/header.html
<!-- {% include './blocks/h_first.html' %} -->
{% load static %}


<div class="main__header__second__mobile__logo">
    <a class="header__second__logo mobile__logo"
    href="{% url 'products:index' %}">
        <img class="logoimg"
        src="{% static 'images/main_logo2.jpg' %}" alt="">
    </a>


</div>

<div class="main__header__second">
    <a class="header__second__logo logo__big"
    href="{% url 'products:index' %}">
        <img class="logoimg"
        src="{% static 'images/main_logo2.jpg' %}" alt="">
    </a>

    <div class="header__second__catalog">
        <div class="header__second__catalog__items">
            <a
            href="{% url 'products:index' %}#delivery__menu__title"
            class="main__anchor__header">
                Меню доставки
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a href="{% url 'products:stock' %}">
                Акции
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'products:index' %}#contact_info_main">
                Контакты
            </a>
        </div>
    </div>

    <div class="main__header__phone">
        <div class="main__header__phone__main">
            <i class="fa fa-phone-alt"></i>
            <div class="main__header__phone__main__text">
                <a href="tel:+78611511254">
                    +7 (861)-151-12-54
                </a>
            </div>
        </div>
        <div class="main__header__phone__callme">
            <span class="main__header__phone__callme">
                Заказать звонок
            </span>
        </div>
    </div>

    <div class="header__second__catalog__mobile">
        <div class="header__second__catalog__mobile__items">
            <i class="gg-menu-left-alt"></i>
            <span>
                Меню
            </span>
        </div>
    </div>

    <div class="main__header__phone__mobile">
        <div class="main__header__phone__main">
            <i class="fa fa-phone-alt"></i>
            <div class="main__header__phone__main__text">
                <a href="tel:+78611511254">
                    +7 (861) 151-12-54
                </a>
            </div>
        </div>
        <div class="main__header__phone__callme">
            <span class="main__header__phone__callme">
                Заказать звонок
            </span>
        </div>
    </div>

    <div class="header__second__icons">

        

        <a class="header__second__icons__item
        header__cart"
        href="{% url 'cart:index' %}">
            <i class="fa fa-shopping-basket
            header__basket"></i>
            <div class="cart__count__info">
                <span class="count__label">
                    {{ cart.items_in_cart }}
                </span>
            </div>
        </a>
        <a class="header__second__icons__item nolink"
        href="{% url 'users:index' %}">
            <i class="fa fa-user"></i>
        </a>
    </div>
</div>


<div class="header__popup__mobile">
    <div class="header__popup__mobile__menu">
        <a href="{% url 'products:index' %}"
            class="mobile__nav">
                Главная
            </a>
        <a
            href="{% url 'products:index' %}#delivery__menu__title"
            class="main__anchor__header
            mobile__nav">
                Меню доставки
            </a>
            <a href="{% url 'products:stock' %}"
            class="mobile__nav">
                Акции
            </a>
            <a
            href="{% url 'products:index' %}#contact_info_main"
            class="mobile__nav">
                Контакты
            </a>
    </div>
</div>
<div class="header__popub__mobile__close">
    <i class="fa fa-close"></i>
</div>
<div class="header__popup__mobile__wrapper">

</div>



<script>
    $(".header__second__catalog__mobile").click(function() {
        openMobileMenu()
    })
    $(".header__popub__mobile__close").click(function() {
        closeMobileMenu()
    })
    $(".mobile__nav").click(function() {
        closeMobileMenu()
    })
</script>

templates/products/index.html
{% extends './base.html' %}

{% block content %}

   {% include './blocks/main__slider.html' %}

   {% comment %} {% include './blocks/space20.html' %}  {% endcomment %}

   {% for category in categories %}
   <div class="cart__main__title">

    <div class="nice__title__center3"
    id="category-{{ category.id }}">
      <span>
        {{ category.name }}
      </span>
    </div>
</div>
{% include './blocks/space20.html' %}

   <div class="products__list__wrapper">

      {% for product in category.product_set.all  %}
         {% include './blocks/product_single.html' %}
      {% endfor %}

   </div>


   {% include './blocks/space20.html' %}

{% endfor %}


   {% include './blocks/contacts.html' %}



   
{% endblock content %}

templates/products/stock.html
{% extends './base.html' %}
{% block content %}
    {% if stocks %}
    <div class="stock__cards">
        {% for stock in stocks  %}
            {% include './blocks/stock_card.html' %}
        {% endfor %}
    </div>
    {% else %}
        {% include './blocks/space20.html' %}
        <div class="empty__cart__container show">

        <div class="favorite__empty"
        id="cart_empty_block">
        {% include './blocks/space20.html' %}
            <span>
                На данный момент акций нет
            </span>
            <p></p>
            {% comment %} Добавьте товар, чтобы он здесь отобразился. {% endcomment %}
            {% include './blocks/space20.html' %}
            <div class="continue__shopping">
                <a id="continue__shopping"
                href="{% url 'products:index' %}">
                    Продолжить покупки
                </a>
            </div>
            {% include './blocks/space20.html' %}
        </div>

        </div>
    {% endif %}
{% endblock content %}

templates/products/stock_item.html
{% extends './base.html' %}
{% load static %}
{% load products_extras %}

{% block content %}

    <div class="stock__item__container">
        <div class="stock__item__img">
            {% modify_imgsrc stock.imgsrc as imgsrc %}
            <img src="{{ imgsrc }}" alt="">
        </div>
        <div class="stock__item__desc">
            <span>
                {{ stock.description }}
            </span>
        </div>
    </div>
{% endblock content %}