api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'api'
urlpatterns = [
    # api requests here,
    path('get_products', views.api_get_allproducts, name='api_get_allproducts'),
    path('get_categories', views.api_get_allcategories, name='api_get_allcategories'),
    path('get_stocks', views.get_stocks, name='get_stocks'),
    path('check_account_exist', views.check_account_exist, name='check_account_exist'),
    path('auth_user', views.auth_user, name='auth_user'),
    path('register_user_request', views.register_user_request, name='register_user_request'),
    path('register_user_finish', views.register_user_finish, name='register_user_finish'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_orders', views.get_user_orders, name='get_user_orders'),
    path('get_user_addresses', views.get_user_addresses, name='get_user_addresses'),
    path('delete_user_address', views.delete_user_address, name='delete_user_address'),
    path('create_user_address', views.create_user_address, name='create_user_address'),
    path('change_user_password', views.change_user_password, name='change_user_password'),
    path('create_order_not_auth', csrf_exempt(views.create_order_not_auth), name='create_order_not_auth'),
    path('create_order_auth', csrf_exempt(views.create_order_auth), name='create_order_auth'),
    path('check_promo', views.check_promo, name='check_promo'),
    path('get_critical_info', views.get_critical_info, name='get_critical_info'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('offer/', views.offer, name = 'offer'),
    path('order_created/', views.order_created, name = 'order_created'),
    path('add_item_ajax/', views.add_item_ajax, name = 'add_item_ajax'),
    path('delete_from_cart_ajax/', views.delete_from_cart_ajax, name = 'delete_from_cart_ajax'),
    path('update_cart_info_ajax/', views.update_cart_info_ajax, name = 'update_cart_info_ajax'),
    path('add_quantity_ajax/', views.add_quantity_ajax, name = 'add_quantity_ajax'),
    path('remove_quantity_ajax/', views.remove_quantity_ajax, name = 'remove_quantity_ajax'),
    path('check_in_cart_ajax/', views.check_in_cart_ajax, name = 'check_in_cart_ajax'),
    path('update_cart_total_ajax', views.update_cart_total_ajax, name = 'update_cart_total_ajax'),
    path('create_order_ajax', views.create_order_ajax, name = 'create_order_ajax'),
    path('process_promo_ajax', views.process_promo_ajax, name = 'process_promo_ajax'),
    path('remove_promo_ajax', views.remove_promo_ajax, name = 'remove_promo_ajax'), 
    path('process_bonus_use_ajax', views.process_bonus_use_ajax, name = 'process_bonus_use_ajax'), 
    path('process_bonus_use_cancel_ajax', views.process_bonus_use_cancel_ajax, name = 'process_bonus_use_cancel_ajax'), 
    path('check_set_delivery_discount_ajax', views.check_set_delivery_discount_ajax, name = 'check_set_delivery_discount_ajax'), 
    path('check_set_payment_ajax', views.check_set_payment_ajax, name = 'check_set_payment_ajax'), 
    path('remember_user_info_ajax', views.remember_user_info_ajax, name = 'remember_user_info_ajax'), 
]

food_fabrik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('products.urls')),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('users.urls')),
] 

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:cat_id>', views.category, name = 'category'),
    path('<int:cat_id>/<int:dest_id>', views.destination, name = 'destination'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('stock/', views.stock, name = 'stock'),
    path('stock/<int:stock_id>', views.stock_item, name = 'stock_item'),
    path('callme_mail_ajax/', views.callme_mail_ajax, name = 'callme_mail_ajax'),
]

users/models.py
from django.db import models


# Create your models here.

def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key  



class User(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    phone = models.CharField(default = None, max_length = 50)
    email = models.CharField(default = None, max_length = 100,
    blank = True, null = True)
    password = models.CharField(default = None, max_length = 200)
    name = models.CharField(default = None, max_length = 100)
    bonus = models.IntegerField(default = 0, 
    null = True, blank = True)

    def __str__(self):
        return self.phone
    def check_password_correct(self, password):
        if self.password == password:
            return True
        else:
            return False
    def set_password(self, password):
        self.password = password
    def get_total_spend(self):
        total_spend = 0
        for order in self.order_set.all():
            # total_spend += order.get_order_cost()
            total_spend += order.amount
        return total_spend
    def get_total_bonus_gained(self):
        return self.bonus
    def calc_user_discount(self):
        total_spend = self.get_total_spend()
        discount = 5
        if total_spend > 5000:
            discount = 7
        if total_spend > 10000:
            discount = 10
        return discount

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
    blank = True, null = True)
    city = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    street = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    house = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    flat = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    comment = models.TextField(default = None, max_length = 1000,
    null = True, blank = True)

    def get_full(self):
        main = self.city + ', ' +  self.street + ' ул. ' +'д. '+ self.house
        if len(self.flat) > 0:
            main += ', кв. ' + self.flat
        return main


def auth_user(username, password):
    if User.objects.filter(
        phone__iexact = username
    ).exists():
        user = User.objects.get(phone = username)
        if user.password == password:
            return user
        else:
            return None
    else:
        return None

def login_user(request, user):
    session_key = get_session_key(request)
    request.session[session_key] = user.id

def login_out_user(request):
    del request.session[request.session.session_key]

def get_user(request):
    session_key = get_session_key(request)
    try:
        user_id = request.session[request.session.session_key]
        user = User.objects.get(id = user_id)
        return user
    except:
        # login_out_user(request)
        return None

def is_authorized(request):
    if request.session.session_key in request.session:
        return True
    else:
        return False

def exist_user(username):
    exist = User.objects.filter(
        phone = username
    ).exists()
    return exist

def register_user(name, username, password):
    user = User(
        name = name,
        phone = username,
        password = password,
    )
    user.save()
    return user

cart/views.py
from django.shortcuts import render

from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from food_fabrik.settings import * 
from products.models import * 

from django.core.mail import send_mail
from django.conf import settings
from django.core import serializers
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from users.models import is_authorized, get_user, Address



def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key

def get_or_create_cart(request):
    session_key = get_session_key(request)
    current_cart = Cart.objects.get_or_create(
        session_key = session_key,
    )[0],
    return current_cart[0]




def index(request):
    session_key = get_session_key(request)
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    total_discount = cart.get_total_discount()
    categories = Category.objects.all()
    return render(request, 'cart/index.html', {
        'categories': categories,
        'cart': cart,
        'session_key': session_key,
        'total_discount': total_discount, 
    })

def offer(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    user = get_user(request)
    categories = Category.objects.all()
    return render(request, 'cart/offer.html', {
        'categories': categories,
        'cart': cart,
        'user': user,
    })

def order_created(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)

    categories = Category.objects.all()
    return render(request, 'cart/order_created.html', {
        'categories': categories,
        'cart': cart,
    })


def add_item_ajax(request):
    cart = get_or_create_cart(request)
    is_new = 'yes'
    pr_id = request.GET['product_id']
    pr = Product.objects.get(
        id = pr_id,
    )
    if (Item.objects.filter(
        product = pr,
        cart = cart,
    ).exists()):
        item = Item.objects.get(
           product = pr,
           cart = cart,
        )
        item.delete()
        in_cart = 'no'
        # item = Item.objects.get(
        #    cart = cart,
        #     pr_id = pr.id, 
        # )
        # item.quantity += 1
        # item.save()
    else:
        item = Item(
            product = pr,
            cart = cart,
        )
        item.save()
        in_cart = 'yes'
    
    return JsonResponse({
        'is_new': is_new,
        'in_cart': in_cart,
        'product_name': pr.name,
    }, status = 200 )

def delete_from_cart_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['item_id']
    item = Item.objects.get(
        cart = cart,
        id = item_id
    )
    item.delete()
    # cart.item_set.remove(item)
    return JsonResponse({
        'deleted': 'yes'
    }, status = 200)

def update_cart_info_ajax(request):
    cart = get_or_create_cart(request)
    cart_total = cart.get_total()
    cart_quantity = cart.item_set.count()
    total_discount = cart.get_total_discount()
    return JsonResponse({
        'cart_total': cart_total,
        'cart_quantity': cart_quantity,
        # 'deleted': 'yes',
        'total_discount': total_discount,
    }, status = 200)

def remove_quantity_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['item_id']
    item = Item.objects.get(
        cart = cart,
        id = item_id,
    )
    if item.quantity == 1:
        item.delete()
        is_removed = 'yes'
        return JsonResponse({
        'is_removed': is_removed,
    }, status = 200)
    else:
        item.quantity -= 1
        item.save()
        is_removed = 'no'
        if (item.has_sale()):
            has_sale = 'yes'
            pr_price = item.product_price()
            pr_sale = item.product_sale_price()
            discount_val = item.discount_val()
            return JsonResponse({
            'has_sale': has_sale,
            'is_removed': is_removed,
            'item_price': pr_price,
            'item_sale': pr_sale,
            'item_discount_val': discount_val,
            'item_quantity': item.quantity,
        }, status = 200)
        else:
            has_sale = 'no'
            pr_price = item.product_price()
            return JsonResponse({
            'has_sale': has_sale,
            'is_removed': is_removed,
            'item_price': pr_price,
            'item_quantity': item.quantity,
        }, status = 200)

        
    

def add_quantity_ajax(request):
    print('request is here')
    cart = get_or_create_cart(request)
    try:
        request.GET['from_prpage']
        item_id = request.GET['item_id']
        item = Item.objects.get(
            cart = cart,
            product__id = item_id,
        )
    except:
        item_id = request.GET['item_id']
        item = Item.objects.get(
        cart = cart,
        id = item_id,
        )

    item.quantity += 1
    item.save()

    if item.has_sale():
        has_sale = 'yes'
        pr_price = item.product_price()
        pr_sale = item.product_sale_price()
        discount_val = item.discount_val()
        return JsonResponse({
            'has_sale': has_sale,
            'item_price': pr_price,
            'item_sale': pr_sale,
            'item_discount_val': discount_val,
            'item_quantity': item.quantity,
        }, status = 200)
    else:
        has_sale = 'no'
        pr_price = item.product_price()
        return JsonResponse({
        'has_sale': has_sale,
        'item_price': pr_price,
        'item_quantity': item.quantity,
    }, status = 200)

def check_in_cart_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['product_id']
    in_cart = ''
    if (Item.objects.filter(
        cart = cart,
        product__id = item_id).exists()):
        in_cart = 'yes'
        current_item = Item.objects.get(
            cart = cart,
            product__id = item_id
        )
        return JsonResponse({
            'in_cart': in_cart,
            'quantity': current_item.quantity,
        }, status = 200)
    else:
        in_cart = 'no'
        return JsonResponse({
            'in_cart': in_cart,
        }, status = 200)


def update_cart_total_ajax(request):
    cart = get_or_create_cart(request)
    cart_total = cart.items_in_cart()
    return JsonResponse({
        'cart_total': cart_total,
    }, status = 200)


def create_order_ajax(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)
    cart_total = cart.items_in_cart()
    purchase_amount = cart.get_total()
    coupon = cart.coupon
    bonus_used = cart.bonus_used
    delivery_discount_use = cart.delivery_discount_use
    # name = urllib.parse.unquote(request.GET['name'])
    # phone = urllib.parse.unquote(request.GET['phone'])
    # delivery = urllib.parse.unquote(request.GET['delivery'])
    # address = urllib.parse.unquote(request.GET['address'])
    # payment = urllib.parse.unquote(request.GET['payment'])

    name = request.GET['name']
    phone = request.GET['phone']
    delivery = request.GET['delivery']
    address = request.GET['address']
    payment = request.GET['payment']

    is_auth = is_authorized(request)
    if (is_auth):
        user = get_user(request)
        if bonus_used:
            user.bonus -= bonus_used
            user.save()
        if coupon:
            coupon.users.add(user)
        if delivery == 'Самовывоз':
            address =  'Самовывоз'
            pass
        else:
            address = Address.objects.get(
                id = delivery
            ).get_full()
            delivery = 'Курьер'
        bonus_gained = calc_bonus_gained(user, purchase_amount)
    else:
        user = None
        bonus_gained = 0
    

    new_order = Order(
        user = user,
        name = name,
        phone = phone,
        delivery = delivery,
        address = address,
        payment = payment,
        bonus_gained = bonus_gained,
        bonus_used = bonus_used,
        amount = purchase_amount,
        coupon = coupon,
        delivery_discount_use = delivery_discount_use,
    )
    new_order.save()
    cart.coupon = None
    cart.bonus_used = None

    # add bonus gained to user and save the user
    # if (is_auth):
    #     user.bonus += bonus_gained
    #     user.save()


    cart_items_mail = []
    order_price_mail = 0
    cart.save()
    for item in cart.item_set.all():
        new_order.item_set.add(item)
        cart.item_set.remove(item)
        if item.has_sale():
            price = item.product.sale_price
        else:
            price = item.product.price
        order_price_mail += price
        cart_items_mail.append([item.product.name, item.quantity, price])
    all_items = new_order.item_set.all()
    new_order.save()
    # try:
    #     email_context = {
    #         'name': name,
    #         'phone': phone,
    #         'order_price': order_price_mail,
    #         'order_items': all_items,
    #         'address': address,
    #         'delivery': delivery,
    #         'payment': payment,
    #     }
    #     admin_html_message = render_to_string('cart/blocks/mail_template.html', email_context)
    #     admin_html_message_plain = strip_tags(admin_html_message)
    #     send_mail(
    #         'Новый заказ на сайте!',
    #         admin_html_message_plain,
    #         settings.EMAIL_HOST_USER,
    #         [
    #         # 'worlddelete0@mail.ru', 
    #         # 'fudfabrik@gmail.com',
    #         # '161085ap@mail.ru',
    #         # 'worlddelete0@yandex.ru',
    #         ],
    #         html_message= admin_html_message,
    #         # 'fudfabrik@gmail.com'
    #         )
    # except:
    #     pass

    return JsonResponse({
        'order_created': 'yes',

templates/cart/blocks/bonus_use_block.html
<!-- promo block is here -->
{% if cart.bonus_used %}
    Вы использовали 
    <span class="main_color">
    {{ cart.bonus_used }}
    </span>
    бонусов для оплаты заказа
    <div class="nice_button font_calc pointer noselect
    bonus_use_button_cancel"
    style="margin: 13px 0px;">
        <span>Отменить</span>
    </div>
    {% else %}
        <div class="promo_container">
        <div>
        Оплата бонусами 
        </div>
        <div>
        У вас на счету 
        <span class="main_color">
        {{ user.bonus }}
        </span>
        бонусов 
        </div>
        </div>
<div class="pay_bonus_msg red"></div>

<div class="flex">
    <input class="input_style1"
    type="text" 
    name="bonus_use_input" 
    placeholder="Введите кол-во бонусов"
    autocomplete="off">
    <div class="nice_button font_calc pointer noselect
    bonus_use_button_submit"
    style="margin: 13px 0px;">
        <span>Списать</span>
    </div>
</div>

{% endif %}


<!-- promo block ends here -->


<script>
    $(".bonus_use_button_submit").click(function() {
        var bonus_to_use = $("input[name='bonus_use_input']").val()
        bonus_to_use = parseInt(bonus_to_use)
        if (bonus_to_use.length < 1) {
            var msg = 'Введите кол-во бонусов'
            $('.pay_bonus_msg').html(msg)
        }
        else if (isNaN(bonus_to_use)) {
            var msg = 'Введите число'
            $('.pay_bonus_msg').html(msg)
        }
        else if (bonus_to_use < 1) {
            var msg = 'Введите положительное число'
            $('.pay_bonus_msg').html(msg)
        }
        else {
            console.log('ready to process promo');
            $.ajax({
                url: "{% url 'cart:process_bonus_use_ajax' %}",
                data: { 
                    'bonus_to_use': bonus_to_use,
                }, success: function(data) {
                    msg = data['msg']
                    var status = data['success']
                    if (status == true) {
                        window.location.reload()
                    } else {
                    $('.pay_bonus_msg').html(msg)
                    }
                }
            })
        }
    })
    $(".bonus_use_button_cancel").click(function() {
        $.ajax({
            url: "{% url 'cart:process_bonus_use_cancel_ajax' %}",
            data: {},
            success: function(data) {
                window.location.reload()
            }
        })
    })
</script>

templates/cart/blocks/checkout_item.html
{% load products_extras %}
<div class="cart__container__products__item"
id="{{ item.id }}">
            
    <div class="cart__container__products__item__info__container">
        {% modify_imgsrc item.product.imgsrc as imgsrc %}
        <img class="cart__container__products__item__img"
    src="{{ imgsrc }}">
        <div class="cart__container__products__item__info">
            <div class="cart__container__products__item__info__name">
                <a href="{% url 'products:product' item.product.id %}">
                    {{ item.product.name }}
                </a>
            </div>
            <div class="cart__container__products__item__info__btns">
            
                
                <div class="cart__container__products__item__btn"
                id="divide__delete"
                style="color: #808d9a;">
                |
                </div>
                <div class="cart__container__products__item__btn
                item__btn__cart item_btn_deletefromcart"
                id="item_btn_deletefromcart"
                value="{{ item.id }}">
                    <span>
                    Удалить
                    </span>
                </div>
            </div>
        </div>
    </div>



    <div class="cart__container__products__item__second__container">

    
    
    <div class="cart__container__products__item__price">

        {% if item.has_sale %}
        
        <div class="cart__container__products__item__price__sale"
        id="saleval{{item.id}}">
            {{ item.product_sale_price }} &#8381;
        </div>
        <div class="cart__container__products__item__price__regular">
            <span class="cart__price__reg1"
            id="reg1price{{item.id}}">
                {{ item.product_price }} &#8381;
            </span>
            <div class="cart__container__products__item__price__regular__disc">
                Скидка 
                <span class="discount__valueset"
                id="discval{{item.id}}">
                {{ item.discount_val }}
                </span>
                 &#8381;
            </div>
        </div>
            {% else %}
            <div class="cart__container__products__item__price__sale"
            id="regval2{{item.id}}">
            {{ item.product_price }} &#8381;
            </div>
        {% endif %}

        
    </div>
    <div class="cart__container__products__item__count">
        <div class="cart__container__products__item__count__main">
        
            <div class="cart__container__products__item__count__main__btn">
                <i class="gg-remove-r
                cart__removequ"
                value="{{ item.id }}"></i>
            </div>
            <div class="cart__container__products__item__count__main__value"
            id="itemqu{{item.id}}">
                {{ item.quantity }}
            </div>
            <div class="cart__container__products__item__count__main__btn">
                <i class="gg-add-r item__addqu" 
                value="{{ item.id }}"></i>
            </div>

        </div>
    </div>


    </div>



</div>

templates/cart/blocks/empty_cart.html
<div class="empty__cart__container">

<div class="favorite__empty"
id="cart_empty_block">
    <span>
        Товаров в корзине не найдено. 
    </span>
    <p></p>
    Добавьте товар, чтобы он здесь отобразился.
    {% include './space20.html' %}
    {% include './space20.html' %}
    <div class="continue__shopping">
        <a id="continue__shopping"
        href="{% url 'products:index' %}">
            Продолжить покупки
        </a>
    </div>
    {% include './space20.html' %}
    {% include './space20.html' %}
    {% include './space20.html' %}
</div>

</div>

templates/cart/blocks/favorite_empty.html
{% include './space20.html' %}
{% include './space20.html' %}
<div class="favorite__empty"
id="favorite_empty_block">
    {% include './space20.html' %}
    {% include './space20.html' %}
    <span>
        Товаров в избранном не найдено. 
    </span>
    <p></p>
    Добавьте товар, чтобы он здесь отобразился.
    {% include './space20.html' %}
    {% include './space20.html' %}
    <div class="continue__shopping">
        <a id="continue__shopping"
        href="{% url 'products:index' %}">
            Продолжить покупки
        </a>
    </div>
    {% include './space20.html' %}
    {% include './space20.html' %}
    {% include './space20.html' %}
</div>

templates/cart/blocks/mail_template.html
{% load static %}
{% load products_extras %}

<h2>
    Новый заказ!  Сумма заказа: {{ order_price }}.
</h2>

<div>
    <table>
        <tr>
            <td class="order_mail_td">
                Статус
            </td>
            <td>
            -->
                Ожидает подтверждения менеджером
            </td>
        </tr>
        <tr>
            <td class="order_mail_td">
                Имя
            </td>
            <td>
            -->
                {{ name }}
            </td>
        </tr>
        <tr>
            <td class="order_mail_td">
                Телефон
            </td>
            <td>
            -->
                {{ phone }}
            </td>
        </tr>
        <tr>
            <td class="order_mail_td">
                Адрес доставки
            </td>
            <td>
            -->
                {{ address }}
            </td>
        </tr>
        <tr>
            <td>
                Способ доставки:
            </td>
            <td>
            -->
                {{ delivery }}
            </td>
        </tr>
        <tr>
            <td>
                Способ оплаты:
            </td>
            <td>
            -->
                {{ payment }}
            </td>
        </tr>

    </table>
    <br> <br>
    <h3>
        Состав заказа:
    </h3>
    <br>
    <table>
        {% for item in order_items %}
            <tr>
                <td>
                    {% modify_imgsrc item.imgsrc as imgsrc %}
                    <img src="{{ imgsrc }}" alt="">     
                </td>
                <td>
                    {{ item.name }} 
                </td>
                <td>
                    {{ item.quantity }} x 
                    {{ item.product_get_prices }}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>

templates/cart/blocks/offer_address_block.html
{% for address in user.address_set.all %}
<div class="cart_delivery_authorized_item">
    <input type="radio"
    class="cart_delivery_authorized_input"
    id="delivery_address_auth_{{ address.id }}"
    name="delivery_address_auth"
    value="{{ address.id }}">
    <label class="pointer offer_address_label"
    for="delivery_address_auth_{{ address.id }}">
        {{ address.get_full }}
    </label>
</div>
{% endfor %}

templates/cart/blocks/promo_block.html
<!-- promo block is here -->
{% if cart.coupon %}
    <div class="promo_container">
    <div>
    Промокод 
    <span class="main_color">
        {{ cart.coupon.code }}
    </span>
     успешно использован!
    </div>
    <div class="nice_button pointer noselect center">
        <span class="promo_delete_button">
            Отменить промокод
        </span>
    </div>
    </div>
{% else %}
<div class="promo_msg"></div>
<div class="input_promo">
    <input class="input_style1"
    type="text" 
    name="promocode_input" 
    placeholder="Промокод"
    autocomplete="off">
    <div class="nice_button font_calc pointer noselect
    promo_button_submit"
    style="margin: 13px 0px;">
        <span>Использовать</span>
    </div>
</div>
<!-- promo block ends here -->

{% endif %}

<script>
    $(".promo_button_submit").click(function() {
        var promo = $("input[name='promocode_input']").val()
        if (promo.length < 1) {
            var msg = 'Поле промокода пусто'
            $('.promo_msg').html(msg)
        } else {
            console.log('ready to process promo');
            $.ajax({
                url: "{% url 'cart:process_promo_ajax' %}",
                data: { 
                    'promo': promo,
                }, success: function(data) {
                    msg = data['msg']
                    var status = data['success']
                    if (status == true) {
                        window.location.reload()
                    } else {
                    $('.promo_msg').html(msg)
                    }
                }
            })
        }
    })
    $(".promo_delete_button").click(function() {
        $.ajax({
            url: "{% url 'cart:remove_promo_ajax' %}",
            data: {}, success: function() {
                window.location.reload()
            }
        })
    })
</script>

templates/cart/blocks/space20.html
<div class="space__20">
    space here
</div>