api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'api'
urlpatterns = [
    # api requests here,
    path('get_products', views.api_get_allproducts, name='api_get_allproducts'),
    path('get_categories', views.api_get_allcategories, name='api_get_allcategories'),
    path('get_stocks', views.get_stocks, name='get_stocks'),
    path('check_account_exist', views.check_account_exist, name='check_account_exist'),
    path('auth_user', views.auth_user, name='auth_user'),
    path('register_user_request', views.register_user_request, name='register_user_request'),
    path('register_user_finish', views.register_user_finish, name='register_user_finish'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('get_user_orders', views.get_user_orders, name='get_user_orders'),
    path('get_user_addresses', views.get_user_addresses, name='get_user_addresses'),
    path('delete_user_address', views.delete_user_address, name='delete_user_address'),
    path('create_user_address', views.create_user_address, name='create_user_address'),
    path('change_user_password', views.change_user_password, name='change_user_password'),
    path('create_order_not_auth', csrf_exempt(views.create_order_not_auth), name='create_order_not_auth'),
    path('create_order_auth', csrf_exempt(views.create_order_auth), name='create_order_auth'),
    path('check_promo', views.check_promo, name='check_promo'),
    path('get_critical_info', views.get_critical_info, name='get_critical_info'),
]

food_fabrik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('products.urls')),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('users.urls')),
] 

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:cat_id>', views.category, name = 'category'),
    path('<int:cat_id>/<int:dest_id>', views.destination, name = 'destination'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('stock/', views.stock, name = 'stock'),
    path('stock/<int:stock_id>', views.stock_item, name = 'stock_item'),
    path('callme_mail_ajax/', views.callme_mail_ajax, name = 'callme_mail_ajax'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('orders/', views.orders, name = 'orders'),
    path('orders/<int:order_id>', views.order_item, name = 'order_item'),
    path('login_ajax', views.login_ajax, name = 'login_ajax'),
    path('login_out_ajax', views.login_out_ajax, name = 'login_out_ajax'),
    path('login', views.login, name = 'login'),
    path('register', views.register, name = 'register'),
    path('settings', views.settings, name = 'settings'),
    path('address', views.address, name = 'address'),
    path('address_action_ajax', views.address_action_ajax, name = 'address_action_ajax'),
    path('promo', views.promo, name = 'promo'),
    path('restore', views.restore, name = 'restore'),
    path('register_ajax', views.register_ajax, name = 'register_ajax'),
    path('restore_ajax', views.restore_ajax, name = 'restore_ajax'),
    path('change_password_ajax', views.change_password_ajax, name = 'change_password_ajax'),
]

cart/models.py
from django.db import models
from users.models import User
from products.models import Product, Category
from users.models import get_user
from django.http import JsonResponse
from django.contrib.humanize.templatetags.humanize import naturalday, naturaltime
from food_fabrik.critical_variables import * 
import time

# Create your models here.

class Coupon(models.Model):
    USAGE_TYPE_CHOICES = [
        ('single', 'Один раз на каждого пользователя'),
        ('multiple', 'Множество раз на каждого'),
    ]
    code = models.CharField(max_length = 100, unique = True)
    # description = models.TextField(default = None,
    # null = True, blank = True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField()
    from_amount = models.IntegerField(default = None,
    null = True, blank = True)
    usage_type = models.CharField(
        max_length = 50,
        choices = USAGE_TYPE_CHOICES,
        default = "single")
    products = models.ManyToManyField(Product,
    null = True, blank = True)
    categories = models.ManyToManyField(Category,
    null = True, blank = True)
    active = models.BooleanField()
    users = models.ManyToManyField(User,
    null = True, blank = True)
    def __str__(self):
        return self.code
    def get_products_list(self):
        return list(self.products.all().values_list('id', flat = True))
    def get_categories_list(self):
        categories_list_ids = list(self.categories.all().values_list('id', flat = True))
        print('self categories list are', categories_list_ids)
        return categories_list_ids
    def check_user(self, request):
        user = get_user(request)
        if user != None:
            return True
        else:
            return False
    def process_cart_coupon(self, request):
        print('self products is', self.products.all())
        print(self.products.all() == None)
        print('self categories is', self.categories.all())
        success = True
        msg = ''
        cart = Cart.objects.get(
            session_key = request.session.session_key
        )
        if self.from_amount:
            if cart.get_total() < self.from_amount:
                success = False
                msg = 'Промокод действует при заказе от {} руб.'.format(self.from_amount)
        if success == True:
            if (not self.products.all().exists()) and (not self.categories.all().exists()):
                success = True
                msg = ''
            elif self.products.all().exists():
                print('self products exists')
                products_pass_ids = []
                coupon_products_ids = self.get_products_list()
                cart_products_ids = cart.get_items_list()
                for item in cart_products_ids:
                    if item in coupon_products_ids:
                        products_pass_ids.append(item)
                if len(products_pass_ids) > 0:
                    success = True
                    msg = "{}".format(products_pass_ids)
                else:
                    success = False
                    msg = 'Промокод не подходит к выбранным товарам'
            if success == False:
                if self.categories.all().exists():
                    print('self categories exists')
                    products_pass_ids = []
                    coupon_categories_ids = self.get_categories_list()
                    print('coupon_categories_ids is ', coupon_categories_ids)
                    # cart_categories_ids = cart.get_items_cat_list()
                    for item in cart.item_set.all():
                        item_category_id = item.product.category.id
                        if item_category_id in coupon_categories_ids:
                            products_pass_ids.append(item.product.id)
                    if len(products_pass_ids) > 0:
                        success = True
                        msg = "{}".format(products_pass_ids)
                    else:
                        success = False
                        msg = 'Промокод не подходит к выбранным товарам'

        if success == True:
            cart.apply_promo(self)
            msg = 'promo added'
        return JsonResponse({
            'success': success,
            'msg': msg,
        }, status = 200)
        
class Favorite(models.Model):
    created_at = models.DateTimeField(auto_now_add = True) 
    session_key = models.CharField(max_length = 200)
    def get_items(self):
        items = self.favoriteitem_set.all()
        return len(items)

class Favoriteitem(models.Model):
    favorite = models.ForeignKey(Favorite, on_delete = models.CASCADE, default = None,
    blank = True, null = True)
    pr_id = models.IntegerField(default = None)

class Cart(models.Model):  
    created_at = models.DateTimeField(auto_now_add = True) 
    session_key = models.CharField(max_length = 200)
    coupon = models.ForeignKey(Coupon, on_delete = models.DO_NOTHING,
    blank = True, null = True)
    bonus_used = models.IntegerField(default = None,
    blank = True, null = True)
    delivery_method = models.IntegerField(default = 1)
    payment_method = models.IntegerField(default = 1)
    delivery_discount_use = models.BooleanField(default = False)
    current_name = models.CharField(default = None, max_length = 200,
    blank = True, null = True)
    current_phone = models.CharField(default = None, max_length = 200,
    blank = True, null = True)

    # def __str__(self):
    #     return self.id
    def check_set_delivery_discount(self):
        if self.coupon:
            pass
        else:
            self.delivery_discount_use = True

    def get_total(self):
        total = 0
        for item in self.item_set.all():
            total += item.get_price()
        if self.bonus_used:
            total = total - self.bonus_used
        if self.delivery_discount_use:
            total = total - int((total * DELIVERY_BYCLIENT_DISCOUNT) / 100)
        return total

    def apply_promo(self, promo):
        self.coupon = promo
        self.save()

    def get_items_list(self):
        items_list = list(self.item_set.all().values_list('product__id', flat = True))
        print('items list are', items_list)
        return items_list
    def get_items_cat_list(self):
        pr_id_list = list(self.item_set.all().values_list('product__id', flat = True))
        products = Product.objects.filter(id__in = pr_id_list)
        # return list(dict.fromkeys(list(products.values_list('category__id', flat = True))))
        cat_id_list = list(products.values_list('category__id', flat = True))
        print('cat id list is ', cat_id_list)
        return cat_id_list
    def items_in_cart(self):
        return len(self.item_set.all())

    def get_total_discount(self):
        products = self.item_set.all()
        total_discount = 0
        for product in products:
            if product.has_sale():
                total_discount += product.discount_val()
        return total_discount
    def get_current_cart(self, request):
        cart = Cart.objects.get(
            session_key = request.session.session_key
        )
        return cart


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('in_progress','В процессе'),
        ('completed','Завершен'),
        ('cancelled','Отменен'),
    ]
    ORDER_DELIVERY_METHODS = [
        ('courier','Доставка курьером'),
        ('byclient','Самовывоз'),
    ]
    ORDER_PAYMENT_METHODS = [
        ('cart','Картой курьеру'),
        ('cash','Наличными'),
    ]


    user = models.ForeignKey(User, on_delete = models.SET_NULL,
    default = None, blank = True, null = True)
    created_at = models.DateTimeField(auto_now_add = True) 
    amount = models.IntegerField(default = 0,
    blank = True, null = True)
    name = models.CharField(max_length = 200, default = '')
    phone = models.CharField(max_length = 50, default = '')
    # email = models.CharField(max_length = 200, default = '')
    delivery = models.CharField(max_length = 200, 
        choices = ORDER_DELIVERY_METHODS,
        default = 'courier'
    )
    address = models.CharField(max_length = 1000, default = '')
    payment = models.CharField(max_length = 200,
        choices = ORDER_PAYMENT_METHODS,
        default = 'cash')
    bonus_gained = models.IntegerField(default = 0, blank = True,
    null = True)
    bonus_used = models.IntegerField(default = None, blank = True,
    null = True)
    coupon = models.ForeignKey(Coupon, on_delete = models.DO_NOTHING,
    blank = True, null = True)
    status = models.CharField(
        max_length = 100,
        choices = ORDER_STATUS_CHOICES, 
        default = 'in_progress'
    )
    delivery_discount_use = models.BooleanField(default = False)
    user_append_bonus = models.BooleanField(default = True)
    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return self.name + ' ' + self.phone

    def save(self, *args, **kwargs):
        print('trigger order save!')
        # print('user is: ', self.user)
        # print('user bonus', self.user.bonus)
        # print('item set are ', self.item_set.all())
        # self.amount = self.calc_amount()
        if self.user != None:
            if self.status == 'completed':
                if self.user_append_bonus:
                    self.user.bonus += self.bonus_gained
                    self.user.save()
        super(Order, self).save(*args, **kwargs)
        # self.amount = self.calc_amount()
        # super(Order, self).save(*args, **kwargs)

    def calc_amount(self):
        total = 0
        for item in self.item_set.all():
            total += item.get_price_ord()
        if self.bonus_used:
            total = total - self.bonus_used
        if self.delivery_discount_use:
            total = total - int((total * DELIVERY_BYCLIENT_DISCOUNT) / 100)
        return total
    def get_order_cost(self):
        cost = 0

users/models.py
from django.db import models


# Create your models here.

def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key  



class User(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    phone = models.CharField(default = None, max_length = 50)
    email = models.CharField(default = None, max_length = 100,
    blank = True, null = True)
    password = models.CharField(default = None, max_length = 200)
    name = models.CharField(default = None, max_length = 100)
    bonus = models.IntegerField(default = 0, 
    null = True, blank = True)

    def __str__(self):
        return self.phone
    def check_password_correct(self, password):
        if self.password == password:
            return True
        else:
            return False
    def set_password(self, password):
        self.password = password
    def get_total_spend(self):
        total_spend = 0
        for order in self.order_set.all():
            # total_spend += order.get_order_cost()
            total_spend += order.amount
        return total_spend
    def get_total_bonus_gained(self):
        return self.bonus
    def calc_user_discount(self):
        total_spend = self.get_total_spend()
        discount = 5
        if total_spend > 5000:
            discount = 7
        if total_spend > 10000:
            discount = 10
        return discount

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
    blank = True, null = True)
    city = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    street = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    house = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    flat = models.CharField(default = None, max_length = 200,
    null = True, blank = True)
    comment = models.TextField(default = None, max_length = 1000,
    null = True, blank = True)

    def get_full(self):
        main = self.city + ', ' +  self.street + ' ул. ' +'д. '+ self.house
        if len(self.flat) > 0:
            main += ', кв. ' + self.flat
        return main


def auth_user(username, password):
    if User.objects.filter(
        phone__iexact = username
    ).exists():
        user = User.objects.get(phone = username)
        if user.password == password:
            return user
        else:
            return None
    else:
        return None

def login_user(request, user):
    session_key = get_session_key(request)
    request.session[session_key] = user.id

def login_out_user(request):
    del request.session[request.session.session_key]

def get_user(request):
    session_key = get_session_key(request)
    try:
        user_id = request.session[request.session.session_key]
        user = User.objects.get(id = user_id)
        return user
    except:
        # login_out_user(request)
        return None

def is_authorized(request):
    if request.session.session_key in request.session:
        return True
    else:
        return False

def exist_user(username):
    exist = User.objects.filter(
        phone = username
    ).exists()
    return exist

def register_user(name, username, password):
    user = User(
        name = name,
        phone = username,
        password = password,
    )
    user.save()
    return user

templates/users/login.html
{% extends '../products/base.html' %}

{% block content %}

<div class="max_width_1 flex">

    <div class="nice_title pd15">
        <span>
            Авторизация
        </span>
    </div>
    
<div class="login_form">
    <div class="login_inputs">
        <input class="input_style1"
        type="text" name="phone" id="phone"
        placeholder="Телефон"
        autocomplete="off">
        <input class="input_style1"
        type="password" name="password"
        placeholder="Пароль"
        autocomplete="off">
    </div>
    <div class="nice_button pointer center">
        <span class="login_button_submit">
            Войти
        </span>
    </div>
    <div class="login_status"></div>
    <div class="restore_password"> 
        <a href="{% url 'users:restore' %}">
            Забыл пароль?
        </a>
    </div>
    <div class="no_account">
        Нет аккаунта? 
        <a href="{% url 'users:register' %}">
            Зарегистрироваться
        </a>
    </div>
</div>

</div>

<script>
    $("#phone").mask("7(999) 999-99-99");
$('.login_button_submit').click(function() {
    var username = $("input[name='phone']").val()
    username = username.replaceAll('(','').replaceAll(')','').replaceAll('-','').replaceAll(' ', '')
    var password = $("input[name='password']").val()
    if ((username.length > 0) && (password.length > 0)) {
            $.ajax({
            url: "{% url 'users:login_ajax' %}",
            data: {
                'username': username,
                'password': password,
            }, success: function(data) {
                var msg = data['message']
                var status = data['success']
                $(".login_status").html(msg)
                if (status) {
                    window.location.href = '/profile/orders'
                }
            }
        })
    } else {
        var msg = 'Заполните все поля'
        $(".login_status").html(msg)
    }
}) 
</script>

{% endblock content %}

templates/users/login_form.html
<h3>Авторизация</h3>
<div class="login_form">
    <input type="text" name="phone" id="phone"
    autocomplete="off">
    <input type="password" name="password"
    autocomplete="off">
    <div class="login_button">
        <span class="login_button_submit">
            login
        </span>
    </div>
    <div class="login_status"></div>
    <div class="restore_password"> 
        <a href="{% url 'users:restore' %}">
            Забыли пароль?
        </a>
    </div>
    <div class="no_account">
        Нет аккаунта? 
        <a href="{% url 'users:register' %}">
            Зарегистрироваться
        </a>
    </div>
</div>

<script>
    $("#phone").mask("7(999) 999-99-99");
$('.login_button_submit').click(function() {
    var username = $("input[name='phone']").val()
    username = username.replaceAll('(','').replaceAll(')','').replaceAll('-','').replaceAll(' ', '')
    var password = $("input[name='password']").val()
    if ((username.length > 0) && (password.length > 0)) {
            $.ajax({
            url: "{% url 'users:login_ajax' %}",
            data: {
                'username': username,
                'password': password,
            }, success: function(data) {
                var msg = data['message']
                var status = data['success']
                $(".login_status").html(msg)
                if (status) {
                    window.location.href = '/profile/orders'
                }
            }
        })
    } else {
        var msg = 'Заполните все поля'
        $(".login_status").html(msg)
    }
}) 
</script>

templates/users/order_item.html
{% extends '../products/base.html' %}
{% load products_extras %}

{% block content %}

    <div class="max_width_1">
    
    {% include './user_head.html' %}


    <div class="order_page">
        <div class="order_info order_block">
            <div class="nice_title medium">
            <span>
                Заказ #{{ order.id }}
            </span>
            </div>
            <div class="nice_title">
            <span>
                Статус заказа: 
                <span class="order_status uppercase mglr15">
                    <span value="{{ order.status }}" class="order_status_value mglr15">
                        {{ order.get_status_display }}
                    </span>
                </span>
            </span>
            </div>
            <div class="nice_title pd15">
            <span>
                Детали доставки
            </span>
            </div>
            <div class="flex pd10">
                <i class="fa fa-user grey delivery_info_icon"></i>
                <div class="info_item medium">
                    <span>{{ order.name }} </span>,
                    <span>{{ order.phone }}</span>
                </div>
            </div>
            <div class="flex pd10">
                <i class="fa fa-map-marker grey delivery_info_icon"></i>
                <div class="info_item regular">
                    <span>{{ order.address }}</span>
                </div>
            </div>
        </div>
        <div class="order_items_block order_block">
            <div class="nice_title medium">
            <span>
                Ваш заказ
            </span>
            </div>
            <div class="order_items_block_container">
                {% for order_item in order.item_set.all %}
                {% modify_imgsrc order_item.product.imgsrc as imgsrc %}
                <div class="order_item_single">
                    <div class="order_item_single_img">
                        <img src="{{ imgsrc }}" alt="">
                    </div>
                    <a href="{% url 'products:product' order_item.product.id %}"
                    class="order_item_single_name">
                        {{ order_item.product.name }}
                    </a>
                    <div class="order_item_single_quantity medium">
                        {{ order_item.quantity }} шт.
                    </div>
                    <div class="order_item_single_price medium">
                        {{ order_item.get_price }} руб.
                    </div>
                    {% comment %} <div class="order_item_single_addcart
                    product__item__addcart"> {% endcomment %}
                        <span class="product__item__addcart
                        product__addtocart__global"
                        value="{{ order_item.product.id }}">
                        {% is_in_cart order_item.product.id cart as in_cart %} 
                            {% if in_cart %}
                            <span class="in__cart__buttonstyle">
                            Удалить с корзины
                            </span>
                            {% else %}
                                <span class="not__incart__buttonstyle">
                                    В корзину
                                </span>
                            {% endif %}
                        </span>
                    {% comment %} </div> {% endcomment %}
                </div>
                {% endfor %}
                {% comment %} eof order_item_single {% endcomment %}
            </div>
        </div>


    </div>


<script>
    setOrderStatusColors()
   $('.user_head').addClass('hide');
   function setOrderStatusColors() {
            orders_status = $(".order_status_value")
            for(i = 0; i < orders_status.length; i++) {
                current_status = $(orders_status[i]).attr("value")
                if (current_status == 'in_progress') {
                    $(orders_status[i]).parent().addClass('progress')
                }
                else if (current_status == 'completed') {
                    $(orders_status[i]).parent().addClass('completed')
                }
                else if (current_status == 'cancelled') {
                    $(orders_status[i]).parent().addClass('cancelled')
                }
                else {
                    $(orders_status[i]).parent().addClass('regular')
                }
            }
        }
</script>
{% endblock content %}

templates/users/orders.html
{% extends '../products/base.html' %}
{% load static %}
{% load products_extras %}

{% block content %}

    <div class="max_width_1">
    {% include './user_head.html' %}

    {% for order in user_orders  %}
        <a href="{% url 'users:orders'%}{{ order.id }}"
        class="order_item pointer nolink">
            <div class="order_item_block">
                <div class="order_id">
                    # {{ order.id }}
                </div>
                <div class="order_status uppercase">
                    <span value="{{ order.status }}" class="order_status_value">
                        {{ order.get_status_display }}
                    </span>
                </div>
            </div>
            <div class="order_item_block order_block_delivery">
                <div class="delivery_title">
                    Адрес доставки
                </div>
                <div class="delivery_address">
                    {{ order.address }}
                </div>
            </div>
            <div class="order_item_block order_cost_first">
                <span>{{ order.get_payment_display }}
                <span class="order_cost">
                    {{ order.amount }}&nbsp;₽
                </span>
                </span>
            </div>
            <div class="order_item_block order_item_block_goods">
                <div class="order_items_titleh">Состав заказа</div>
                <div class="order_cost_last">
                    {{ order.payment }} {{ order.get_order_cost }}&nbsp; ₽
                </div>
                <div class="order_items">
                    {% for item in order.item_set.all %}
                    {% modify_imgsrc item.product.imgsrc as imgsrc %}
                        <img src="{{ imgsrc }}" />
                    {% endfor %}
                </div>
            </div>
        </a>
    {% endfor %}

    </div>

    <script>
        setOrderStatusColors()
        $("#orders_link").parent().addClass('active')
        $(".change_password_button").click(function() {
            openChangePasswordForm()
        })

        function setOrderStatusColors() {
            orders_status = $(".order_status_value")
            for(i = 0; i < orders_status.length; i++) {
                current_status = $(orders_status[i]).attr("value")
                if (current_status == 'in_progress') {
                    $(orders_status[i]).parent().addClass('progress')
                }
                else if (current_status == 'completed') {
                    $(orders_status[i]).parent().addClass('completed')
                }
                else if (current_status == 'cancelled') {
                    $(orders_status[i]).parent().addClass('cancelled')
                }
                else {
                    $(orders_status[i]).parent().addClass('regular')
                }
            }
        }
    </script>

{% endblock content %}

templates/users/promo.html
{% extends '../products/base.html' %}

{% block content %}

 <div class="max_width_1">
 
    {% include './user_head.html' %}

    <div class="nice_title small pd15">
        <span>
            Список использованных промокодов:
        </span>
    </div>
    {% if user.coupon_set.all|length == 0 %}
        <div>
            Ваш список использованных промокодов пуст!
        </div>
        {% else %}
        {% for coupon in user.coupon_set.all  %}
            <div class="promo_item flex">
                <div>
                <div class="regular_title">
                    Промокод:
                </div>
                <div class="semibold_title">
                    {{ coupon.code }}
                </div>
                </div>
                <div class="mglr15">
                <div class="regular_title">
                    Тип промокода:
                </div>
                <div class="semibold_title">
                    {{ coupon.get_usage_type_display }}
                </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>




<script>
    $(".changepass_button_submit").click(function() {
        openChangePasswordForm()
    })
    $("#promo_link").parent().addClass("active")
</script>

{% endblock content %}

templates/users/restore.html
{% extends '../products/base.html' %}

{% block content %}

<div class="max_width_1 flex">

    {% include './restore_form.html' %}

</div>

{% endblock content %}

templates/users/user_head.html
{% load static %}
<div class="user_head">
    <div class="user_head__block user_head__block1">
        <div class="user_head__block__title">
            Привет, {{ user.name }}
        </div>
        <div class="user_head__block__phone">
            {{ user.phone }}
        </div>
    </div>
    <div class="user_head__block flex flex-center">
        <img class="user_head__block__bonusicon"
        src="{% static 'images/bonus_icon.svg' %}" alt="">
        <div class="user_head__block__bonusinfo uppercase">
            <div class="user_head__block__bonuscount">
                {{ user.get_total_bonus_gained }}
            </div>
            бонусов
        </div>
    </div>
</div>

<div class="user_head_links">
    <div class="user_head_link">
        <a class="nolink" id="orders_link"
        href="{% url 'users:orders' %}">
            Заказы {{ user.order_set.count }}
        </a>
    </div>
    <div class="user_head_link">
        <a class="nolink" id="promo_link"
        href="{% url 'users:promo' %}">
            Промокоды
        </a>
    </div>
    <div class="user_head_link">
        <a class="nolink" id="address_link"
        href="{% url 'users:address' %}">
            Адреса
        </a>
    </div>
    <div class="user_head_link">
        <a class="nolink" id="settings_link"
        href="{% url 'users:settings' %}">
            Настройки
        </a>
    </div>
</div>